# 开发环境配置
server:
  port: 8080
springdoc:
  paths-to-match: /**
  paths-to-exclude: /error/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: http://localhost:8086
    user: cbq
    password: cbq.0515
  mail:
    host: smtp.163.com
    username: 15340791287@163.com
    password: PMFQPODUGZIJJZBT
  rabbitmq:
    addresses: localhost
    username: cbq
    password: cbq
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: cbq.monitor
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_