version: '3.7'

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "cbq"
      DOCKER_INFLUXDB_INIT_PASSWORD: "cbq.0515"
      DOCKER_INFLUXDB_INIT_ORG: "cbq"
      DOCKER_INFLUXDB_INIT_BUCKET: "test"

  mysql8_3306:
    image: mysql:8.0
    container_name: mysql8_3306
    ports:
      - "3306:3306"
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "monitor"
    command:
      - "mysqld"

  redis_6379:
    image: redis
    container_name: redis_6379
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "cbq"
      RABBITMQ_DEFAULT_PASS: "cbq"

volumes:
  influxdb2-data:
  influxdb2-config:
  rabbitmq-home:
