@startuml
!theme plain

actor 用户
participant 前端
participant 后端

用户 -> 前端 : 请求发送验证码
前端 -> 后端 : POST /api/auth/ask-code
alt 发送失败
    后端 -> 前端 : 验证码发送失败
    前端 -> 用户 : 显示验证码发送失败信息
else 发送成功
    后端 -> 前端 : 验证码发送成功
    前端 -> 用户 : 显示验证码发送成功请注意查收信息
    用户 -> 前端 : 输入username, password, email, code
    前端 -> 前端 : 校验输入信息
    alt 校验失败
        前端 -> 用户 : 显示校验失败信息
    else 校验成功
        前端 -> 后端 : POST /api/auth/register
        后端 -> 后端 : 通过FlowLimitingFilter校验IP
        alt 被限流
            后端 -> 前端 : 操作频繁，请稍后再试
            前端 -> 用户 : 显示操作频繁信息
        else IP放行
            后端 -> 后端 : 校验验证码
            alt 验证码为null
                后端 -> 前端 : 请先获取验证码
                前端 -> 用户 : 显示请先获取验证码信息
            else 验证码错误或过期
                后端 -> 前端 : 验证码错误或过期
                前端 -> 用户 : 显示验证码错误或过期信息
            else 验证码正确
                后端 -> 后端 : 判断email是否被注册
                alt 邮箱已注册
                    后端 -> 前端 : 该邮箱地址已注册
                    前端 -> 用户 : 显示该邮箱地址已注册信息
                else 邮箱未注册
                    后端 -> 后端 : 加密密码并保存账户
                    alt 保存成功
                        后端 -> 前端 : 注册成功
                        前端 -> 用户 : 显示注册成功并跳转至登录页面
                    else 保存失败
                        后端 -> 前端 : 内部错误、注册失败
                        前端 -> 用户 : 显示内部错误、注册失败信息
                    end
                end
            end
        end
    end
end

@enduml
